### ISSUE TITLE
Guard against missing directory when running commands

### ISSUE THREAD

**Issue by brettbuddin** [stuartcarnie/gopm#16]
## What

We recently encountered an issue where the `directory` specified for a program was incorrect. This lead to a misleading error message of `fork/exec /bin/zsh: no such file or directory`. This threw us down a rabbit hole of thinking it was the actual shell that was the problem. Instead, the `directory` was set to a path that did not exist.

## How

Let's guard against this condition and `os.Stat` the `directory` specified before starting the command. We'll be able to provide a much more clear error message this way. Calling `os.Stat` at the top of this function will suffice.

https://github.com/stuartcarnie/gopm/blob/f504d9ab6ea844a0b4ccde9103b81fca09a300a9/process/process.go#L673-L678

**Comment by yquansah** [comment]
PR Opened for this issue: https://github.com/stuartcarnie/gopm/pull/17
