### ISSUE TITLE
caddy 2.4.3 fails to parse root/caddy/Caddyfile

### ISSUE THREAD

**Issue by jdstrand** [stuartcarnie/gopm#24]
caddy 2.3.0 would parse the generated root/caddy/Caddyfile ok, but with a deprecation warning:
```
{"level":"warn","ts":1625168095.5196342,"logger":"caddy.logging.encoders.logfmt","msg":"the logfmt encoder is DEPRECATED and will soon be removed from the standard modules","recommendation":"switch to a log format that isn't broken","more_info":"https://github.com/caddyserver/caddy/issues/3575"}
```

caddy 2.4.3 now fails to parse the file with:
```
run: adapting config using caddyfile: parsing caddyfile tokens for 'log': /path/to/root/caddy/Caddyfile:10 - Error during parsing: getting module named 'caddy.logging.encoders.logfmt': module not registered: caddy.logging.encoders.logfmt
```

Downgrading to 2.3.0 via https://github.com/caddyserver/caddy/releases/tag/v2.3.0 resolves the issue. https://github.com/caddyserver/caddy/issues/3575 claims that "the logfmt module will still be available, but not by default, as it is essentially broken. Instead of sweeping the bug under the rug, this will call it out to attention, which is better." but that seems to conflict with this change in 2.4.3: https://github.com/caddyserver/caddy/commit/ef5448324948537bb4ce798567d79d0612d41220.

**Comment by jdstrand** [comment]
For apt users on Linux, after installing the 2.3.0 deb, you can keep the caddy site in your sources.list and pin caddy by creating `/etc/apt/preferences.d/caddy.pref` like so until this issue is resolved:
```
Package: caddy
Pin: version 2.3.0
Pin-Priority: 1001
```

**Comment by stuartcarnie** [comment]
@jdstrand this is actually an issue with the configuration file, not gopm. I will share a fix with you

**Comment by jdstrand** [comment]
> @jdstrand this is actually an issue with the configuration file, not gopm. I will share a fix with you

Oh, yes, I would be interested. Are you referring to this section in my idpe.yaml:
```
filesystem:
  root: ${IDPE_CLUSTER_ROOT}
  files:
    - name: CADDYFILE
      path: caddy/Caddyfile
...
        log {
            output stdout
            level DEBUG
            format logfmt
        }
...
```

Whether it is that or something else in idpe.yaml, happy to take that and do a PR for contrib/gopm.

**Comment by jdstrand** [comment]
> > @jdstrand this is actually an issue with the configuration file, not gopm. I will share a fix with you
> 
> Oh, yes, I would be interested. Are you referring to this section in my idpe.yaml:
> 
> ```
> filesystem:
>   root: ${IDPE_CLUSTER_ROOT}
>   files:
>     - name: CADDYFILE
>       path: caddy/Caddyfile
> ...
>         log {
>             output stdout
>             level DEBUG
>             format logfmt
>         }
> ...
> ```
> 
> Whether it is that or something else in idpe.yaml, happy to take that and do a PR for contrib/gopm.

Indeed, I can simply remove `format logfmt` from the log stanza and it works with 2.4.3. This will default to 'console' (human readable) if it detects a terminal or json otherwise. This results in different output for the access log (ie, hitting caddy's open port (8080 with idpe template config)):
```
# 2.3.0 'format logfmt'
ts=1625771456.3908355 level=error msg="handled request" requestError="unsupported value type" common_log="127.0.0.1 - - [08/Jul/2021:14:10:56 -0500] \"GET / HTTP/1.0\" 404 0" duration=0.000112204 size=0 status=404 resp_headersError="unsupported value type"
```
vs
```
# default 'format'
http.log.access.log0	handled request	{"request": {"remote_addr": "127.0.0.1:39402", "proto": "HTTP/1.0", "method": "GET", "host": "localhost:8080", "uri": "/", "headers": {"User-Agent": ["w3m/0.5.3+git20190105"], "Accept": ["text/html, text/*;q=0.5, image/*, application/*, x-scheme-handler/*"], "Accept-Encoding": ["gzip, compress, bzip, bzip2, deflate"], "Accept-Language": ["en;q=1.0"]}}, "common_log": "127.0.0.1 - - [08/Jul/2021:14:17:38 -0500] \"GET / HTTP/1.0\" 404 0", "duration": 0.00042133, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy"]}}
```

Personally, I think the json output is just fine since nothing is parsing the caddy access logs that I know of. I'll create a PR against IDPE.

Thanks!
